version: "3.9"
services:
  asgard-be-movie-service:
    image: asgard-be-movie-service:main
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DB_URL: db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      TMDB_API_TOKEN: a
      TMDB_URL: http://mockoon:4000
    healthcheck:
      test: curl -f https://localhost:3000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  mockoon:
    image: mockoon/cli:latest
    depends_on:
      asgard-be-movie-service:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./db/mockoon/mock.json
        target: /data
    command: -d data -p 4000
    ports:
      - '4000:4000'