# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test application on PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test-application:
    name: Build and Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          push: false
          tags: asgard-be-movie-service:main
      - name: Run application and DB
        run: docker-compose -f ./db/docker-compose.yaml up -d
      - name: Postgres Backup Restore
        uses: tj-actions/pg-restore@v4.8
        with:
          database_url: "postgres://postgres:postgres@localhost:5432/postgres"
          backup_file: "./db/asgard.dump"
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - uses: matt-ball/newman-action@master
        id: postman-test
        with:
          collection: ./db/postman/4sgard portal.postman_collection.json
          environment: ./db/postman/DEV.postman_environment.json
        continue-on-error: true
      - name: Check on failures
        if: steps.postman-test.outcome != 'success'
        run: |
          cd db/
          docker-compose logs
          exit 1
